In [1]:
import cv2
import numpy as np

# Load the two images
image1 = cv2.imread('imag1.jpg')
image2 = cv2.imread('imag2.jpg')

# Ensure both images are the same size
if image1.shape != image2.shape:
    print("Error: Images must have the same dimensions.")
else:
    # Compute the absolute difference between the two images
    output_image = cv2.absdiff(image1, image2)
    print(output_image)

    # Display the output image
    cv2.imshow("Absolute Difference", output_image)

    # Wait until a key is pressed and close the windows
    cv2.waitKey(0)
    cv2.destroyAllWindows()


[[[27 35 27]
  [28 36 28]
  [30 38 30]
  ...
  [ 9  1  8]
  [11  1  8]
  [11  1  8]]

 [[29 37 29]
  [30 38 30]
  [32 40 32]
  ...
  [ 9  1  8]
  [10  2  9]
  [10  2  9]]

 [[32 40 32]
  [33 41 33]
  [34 42 34]
  ...
  [ 8  2  9]
  [ 9  3 10]
  [10  2  9]]

 ...

 [[16 25 23]
  [16 25 23]
  [16 25 23]
  ...
  [ 6  8 13]
  [ 5  9 14]
  [ 4 10 15]]

 [[15 24 22]
  [15 24 22]
  [16 25 23]
  ...
  [ 6  8 13]
  [ 2 10 15]
  [ 1 11 16]]

 [[15 24 22]
  [15 24 22]
  [16 25 23]
  ...
  [ 5  9 14]
  [ 2 10 15]
  [ 1 11 16]]]


In [7]:
import cv2
import numpy as np
from skimage.feature import hog
from skimage import exposure

# Load and preprocess the image to 64x128
image = cv2.imread('imag1.jpg', cv2.IMREAD_GRAYSCALE)
image = cv2.resize(image, (64, 128))

# Step 2: Calculate Gradients (x and y directions)
gradient_x = cv2.Sobel(image, cv2.CV_64F, 1, 0, ksize=1)
gradient_y = cv2.Sobel(image, cv2.CV_64F, 0, 1, ksize=1)

# Step 3: Calculate the Magnitude and Orientation
magnitude = np.sqrt(gradient_x**2 + gradient_y**2)
orientation = np.arctan2(gradient_y, gradient_x) * (180 / np.pi) % 180  # Converting to degrees in [0, 180]

# Step 4 & 5: Calculate Histogram of Gradients in 8×8 cells and normalize in 16×16 cells
# Define HOG parameters
cell_size = (8, 8)    # Each cell is 8x8 pixels
block_size = (2, 2)   # Each block contains 2x2 cells (16x16 pixels)
nbins = 9             # Number of orientation bins

# Compute HOG features
hog_features, hog_image = hog(image,
                              orientations=nbins,
                              pixels_per_cell=cell_size,
                              cells_per_block=block_size,
                              block_norm='L2-Hys',
                              visualize=True,
                              transform_sqrt=True)

print(hog_features)

# Step 6: Display HOG features for the complete image
hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 10))

# Show original and HOG images
cv2.imshow("Original Image", image)
cv2.imshow("HOG Features", hog_image_rescaled)
cv2.waitKey(0)
cv2.destroyAllWindows()


[0.38221026 0.01697378 0.00441307 ... 0.11042884 0.12213421 0.25482789]
